#!/bin/bash

alphabets=("a" "b" "c" "d" "e" "f" "g" "e" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s" "t" "u" "v" "w" "x" "y" "z")
i=0

for i in "${!alphabets[@]}"; do
    find SWE_2021_41_2023_2_week_4-main/files -iname "${alphabets[i]}*" ! -name "files" -exec mv -f {} SWE_2021_41_2023_2_week_4-main/${alphabets[i]} \;
    done

